name: Update Posts

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install requests (if needed)
        run: pip install requests

      - name: Fetch from Telegram
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python fetch_telegram.py

      - name: Commit and push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add posts.json
          git diff --cached --quiet || git commit -m "Update posts.json"
          git push https://x-access-token:${GH_TOKEN}@github.com/diffw/my-thoughts-bot.git HEAD:main
